# Generated by Django 3.0.4 on 2020-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_auto_20200408_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
